require "test_helper"

class DataImportExportRoundTripTest < ActiveSupport::TestCase
  test "imports transactions from JSON generated by data export" do
    source_user = create(:user)
    target_user = create(:user)
    source_account = create_account(user: source_user, name: "Cash", balance_cents: 0)
    create_account(user: target_user, name: "Cash", balance_cents: 5_000)
    source_category = create_category(user: source_user, name: "Food", category_type: :expense)
    create_category(user: target_user, name: "Food", category_type: :expense)
    source_tag = create_tag(user: source_user, name: "Business")
    create_tag(user: target_user, name: "Business")
    transaction = create_transaction(user: source_user, account: source_account, category: source_category, tag: source_tag)
    exported_json = DataExport.new.transactions_json(user: source_user)
    batch = ImportBatch.create!(user: target_user, source_filename: "transactions.json", raw_csv: exported_json)

    ImportFileParser.new.parse_import_batch(import_batch: batch)
    TransactionImporter.new.import_transactions(import_batch: batch)

    assert_predicate batch.reload, :imported?
    imported_transaction = target_user.transactions.sole
    assert_equal transaction.comment, imported_transaction.comment
    assert_equal transaction.source_amount_cents, imported_transaction.source_amount_cents
    assert_equal transaction.transaction_kind, imported_transaction.transaction_kind
    assert_equal transaction.timezone_utc_offset_minutes, imported_transaction.timezone_utc_offset_minutes
    assert_equal transaction.hide_amount, imported_transaction.hide_amount
    assert_equal transaction.geo_latitude, imported_transaction.geo_latitude
    assert_equal transaction.geo_longitude, imported_transaction.geo_longitude
    assert_equal [ "Business" ], imported_transaction.transaction_tags.map(&:name)
    assert_equal 3_800, target_user.accounts.find_by!(name: "Cash").balance_cents
  end

  private

  def create_account(user:, name:, balance_cents:)
    Account.create!(
      user: user,
      name: name,
      account_category: :cash,
      account_structure: :single_account,
      icon_key: 1,
      color_hex: "22C55E",
      currency_code: "USD",
      balance_cents: balance_cents,
      display_order: 1
    )
  end

  def create_category(user:, name:, category_type:)
    TransactionCategory.create!(
      user: user,
      name: name,
      category_type: category_type,
      icon_key: 1,
      color_hex: "F97316",
      display_order: 1
    )
  end

  def create_tag(user:, name:)
    TransactionTag.create!(user: user, name: name, display_order: 1)
  end

  def create_transaction(user:, account:, category:, tag:)
    transaction = Transaction.create!(
      user: user,
      account: account,
      transaction_category: category,
      transaction_kind: :expense,
      transacted_at: Time.zone.parse("2026-05-03 10:00:00"),
      timezone_utc_offset_minutes: 480,
      source_amount_cents: 1_200,
      destination_amount_cents: 0,
      hide_amount: true,
      comment: "Client lunch",
      geo_latitude: 37.7749,
      geo_longitude: -122.4194
    )
    transaction.transaction_taggings.create!(user: user, transaction_tag: tag)
    transaction
  end
end
